apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nodejssimpleappfront2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nodejssimpleappfront2
    spec:
      containers:
      - name: nodejssimpleappfront2
        image: welasco/nodejssimpleapp:latest
        ports:
        - containerPort: 3000
          name: front2
        env:
        - name: envbackend
          value: "nodejssimpleappback"
        - name: envPort
          value: "3008"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejssimpleappfront2
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 3008
  selector:
    app: nodejssimpleappfront2