apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: testapi 
spec:
  replicas: 1
  selector:
    matchLabels:
      application: testapi  
  template:
    metadata:
      labels:
        app: testapi
    spec:
      containers:
      - name: testapi
        image: welasco/nodejssimpleapp:latest
        env:
        - name: envPort
          value: "8080"          
---
apiVersion: v1
kind: Service
metadata:
  name: testapi 
  namespace: default
  labels:
    application: testapi   
spec:
  type: NodePort
  selector:
    application: testapi   
  ports:
  - port: 8080
    targetPort: 8080 
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: testapi
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "testapi.hepoca.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: testapi
          servicePort: 8080    